import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Dialog from "./components/Dialog";
import TransactionForm from "./components/Form";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Dialog title="Example Modal">
          <TransactionForm />
        </Dialog>
      </body>
    </html>
  );
}
